### ISSUE TITLE
Instrument scientists and round managers will be able to access submitted proposals only for their facility or facility area

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#1]
Instrument scientists and round managers will be able to access all submitted proposals for their facility or facility area to support users submitting proposals and to review proposal technical feasibility

Impacted users: Instrument Scientists, Proposal round managers

Project requirement: [proposal-4](https://stfc365.sharepoint.com/sites/proposals-and-outcomes-transformation-programme/Lists/Proposal%20user%20stories/DispForm.aspx?ID=4)

**Comment by TickleThePanda** [comment]
I think there's a few different ways we can approach this and it will need a form of design review. In this issue, when I refer to _call_, I mean round. 

This permissions referred to in this issue are related to how the user office create and modify calls and questionnaires or how they or instrument scientists view submitted proposals.

### Manage different permissions per call

This would add additional configuration to each call to give permissions to the appropriate groups. Overall, this would add complexity to the functionality around calls or to other areas of the software.

I'm aware that the SWAP team were apprehensive about the complexity here but I think it is worth discussion.

If we are to approach it from this direction - we should considering that we structure of groups for permissions to allow for flexibility. From our point of view we see "facilities" as what defines the permission for each call but it might fit future needs if it's abstracted in a different way (defining teams or groups).

### Have multiple instances with different permissions

For this option, we would have multiple instances and we would modify the way that we translate the UOWS roles to the UOP roles. This would add complexity to our role translation and the roles needed in the UOWS and would add complexity to our deployment environment.

---

These are not the only options available to us but are my thoughts that I've had so far - I'd be happy to hear other suggestions.

**Comment by TickleThePanda** [comment]
I've moved this to ISIS Rapid as we won't need to handle this until that point.

**Comment by TickleThePanda** [comment]
> Manage different permissions per call

For this option, Fredrik has asked if we can come up with a proposal (or proposals) on how we might approach this.

**Comment by mr-field** [comment]
Some notes from a deep dive into this.

### What we want
We want STFC instrument scientists to only see proposals for their facility (ISIS, CLF/CLF subfacilities). Each facility has one or more instruments and is managed by a different user office.

### Current situation
When running in STFC config, instrument scientists can see all calls and all proposals. In ESS mode, instrument scientists can only see the calls and proposals assigned to their assigned instruments. This is a result of STFC using patched datasources for [Calls](https://github.com/UserOfficeProject/user-office-backend/blob/c38ba970d03081255d89f5e26e43b8c89e07543a/src/datasources/stfc/StfcCallDataSource.ts#L7) and [Proposals](https://github.com/UserOfficeProject/user-office-backend/blob/c38ba970d03081255d89f5e26e43b8c89e07543a/src/datasources/stfc/StfcProposalDataSource.ts#L15). These were added as quick fixes to let instruments scientists see all proposals in the first round, but could be avoided if instrument scientists and calls were correctly assigned to instruments.

The app doesn't have a concept of a facility, but it can assign multiple instruments to a call and multiple instruments to an instrument scientist. This could be used as a quick way of approximating facilities.

**Note**: at the moment, the dialog to assign instrument scientists to an instrument is broken (as is the one to assign a beamline manager to an instrument). This should be fixed by https://github.com/UserOfficeProject/user-office-backend/pull/553 and https://github.com/UserOfficeProject/user-office-frontend/pull/674.

### Quick fix
The quickest fix for this is to use the same (or a very similar) logic used by the ESS:
- Remove the STFC `CallDataSource` to restrict instrument scientists to calls assigned to their instruments
- Either remove the STFC `ProposalDataSource`, or tweak it to show only proposals submitted to a call assigned to the scientist's instruments
- Create all instruments we need
- Assign instrument scientists to instruments
- Ask the User Office to assign every call they create to all instruments for the call's facility

On the last point, the ESS `ProposalDataSource` requires the proposals themselves to have been assigned to the scientist's instrument - it's not enough to be submitted to a call assigned to the scientist's instrument. If we used the ESS datasource, a User Officer would have to assign all proposals to their requested instrument after submission, which could be too impractical. We may prefer to tweak our own datasource to filter proposals by call assigned to an instrument, instead of checking if the proposal itself is assigned to the instrument.

This is a fairly easy fix, but it may be hard for the User Office as facilities can have dozens of instruments. It would be easier if instruments were grouped together in different facilitites.

### Bigger fix
We could introduce the concept of a facility to the app. For the purposes of this issue, a facility is basically an instrument group:
- Add a `Facility` table to the DB, complete with its own datasource and model class
- Add datasource methods and GraphQL mutations to view and edit facilities, as well as assigning them to calls, instruments, and (maybe) proposals. We also need to assign instrument scientists to facilities
- Change the Calls and Proposals datasources to look at assigned facilities, rather than/in addition to assigned instruments when getting calls and proposals for instrument scientists
- Add a new frontend page for viewing and editing facilities, as well as new controls for assigning objects to facilities
- Create all instruments and facilities we need
- Assign instrument scientists and instruments to facilities
- Ask the User Office to assign every call they create to a facility (could be made compulsory)

This is a larger change, and it will need some consideration to avoid imposing too much complexity on the ESS (which doesn't need multiple facilities). The main advantage is that instruments and instrument scientists can now be added and removed from facilities with only a couple of clicks, rather than requiring assignement to dozens of different objects.

Another advantage of this is that it might be useful to STFC in the future, as facilities tend to come up in a lot of our processes. For example, it might help with https://github.com/UserOfficeProject/stfc-user-office-project/issues/40.

**Comment by mr-field** [comment]
Having made some progress with adding Facilities, it feels like I'm simply duplicating Instruments. At the moment, Facilities work in exactly the same way as Instruments (i.e. they're objects which can be assigned to calls and people to grant permissions on proposals) with the only added bonus that they can also be assigned to Instruments, becoming a sort of instrument group. However, this doesn't really have any advantages for STFC at the moment. All calls are submitted to facilities and users can't directly choose the instrument they're sending the proposal to. At most, they can choose an "instrument" from a dropdown question but this wouldn't assign the proposal to that instrument (and the list of instrument wouldn't be read from the app's Instrument but set manually).

Facilities may be useful to us if we're planning to add a question type which automatically lists all instruments in a facility and lets to user choose one, with automatic assignment at the end. However, it is uncler if this would have any significant advantages over simply providing a hardcoded list of instruments.

**Comment by mr-field** [comment]
We had a design review about this on 09/05/2022 and decided to avoid introducing Facilities for now. We will add STFC facilities as Instruments instead and link them to STFC users through Active Directory groups.
