### ISSUE TITLE
As an Xpress scientist, I want to select a range of proposals by date and export their proposal and sample summaries to a file

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#1028]
This is to replicate the existing legacy function where the user can download a `.tsv` file containing a range of proposals' proposal and sample summaries.

The file format can be a common file format and doesn't necessarily need to be `.tsv`.

--- 

![image](https://github.com/UserOfficeProject/issue-tracker/assets/14293717/0b83e798-b382-4725-9ec4-9ed1b065ac46)

**Comment by simonfernandes** [comment]
Hi @Cat-Lucifer, please could you advise on a couple of things around this:

- In the management page, should user officers and/or scientists see unsubmitted Xpress proposals?
- Should the date range export only include submitted proposals?

The reason for asking is that our plan was to offer a date filter along the top of the table (from date and to date) that would filter which proposals show in the table. The scientist would then click the "tick all" button to select all rows and then click the export button. But this approach doesn't really work if the table includes unsubmitted proposals and the export should only include submitted.

**Comment by Cat-Lucifer** [comment]
@simonfernandes   Good questions!  I think UO can see everything and should be able to export everything.  I think it's okay for scientists to see unsubmitted proposals for their specific technique (so once a technique is selected in a draft I guess).

**Comment by simonfernandes** [comment]
Thanks @Cat-Lucifer. Did you mean that scientists should see unsubmitted proposals (in the list) **and** should see them in the exported data?

**Comment by Cat-Lucifer** [comment]
@simonfernandes  Sorry, I should have been more clear.  Yes, that would be ideal.  If it's easier to export the data without the draft proposals though then do that.

**Comment by simonfernandes** [comment]
Notes from review meeting with Deepak and Emma:

Expired proposals should be excluded in the export.

**Comment by deepaksftc** [comment]
Hi @Cat-Lucifer, on analysing this issue further, since we do not have a restriction on the type of the file and the data currently exported from legacy system is similar to the data in proposal pdfs downloaded (from new system), I just wanted to check with you that, if downloading selected proposal pdfs in a single pdf could be an alternative? Or it should be in an excel kind of format itself?

And also, these were the fields that I found in one of the exported file from legacy system.
Title	
RB Number	
Science Programmes	
Exposure Time	
Last Modified	
Status	
Experimenter	
Institute	
Country	
Sample Material	
Sample Types	
Chemical Formula	
Mass (ml/gm)	
Storage Requirements	
Hazards	Hazard Details	
Sensitive to Air?	
Sensitive to Water?	
Disposal Method	
Sample Can Size	
Sample Can Reference	
Ship Date

And these are the fields that the 'export proposals in excel' function in user-officer page returns for selected proposals.
Proposal ID	
Title	
Principal Investigator	
Instrument	
Technical Status	
Technical Comment	
Time(Days)	
Comment 
Management	Decision

If we are going to export into excel format, could you please help me decide which all fields would need to be included?

**Comment by Cat-Lucifer** [comment]
@deepaksftc Please could you pop in a quick meeting to discuss?  I have no idea what can be downloaded in the current system, what it looks like, is it common for all instruments, etc.  Honestly, I have little to no knowledge of this part of Xpress...

**Comment by deepaksftc** [comment]
> @deepaksftc Please could you pop in a quick meeting to discuss? I have no idea what can be downloaded in the current system, what it looks like, is it common for all instruments, etc. Honestly, I have little to no knowledge of this part of Xpress...

Sure @Cat-Lucifer, I will schedule a call to discuss this.

**Comment by simonfernandes** [comment]
@Cat-Lucifer @deepaksftc I've created https://github.com/UserOfficeProject/issue-tracker/issues/1206 for creating reporting to replace this functionality

**Comment by deepaksftc** [comment]
Hi @Cat-Lucifer, just wanted to clarify about our conclusion. We will have an option to export the proposals into excel sheet with all the fields available in the management page table. 
The fields that will be available in excel will be,
    'Proposal ID',
    'Title',
    'Principal Investigator',
    'PI Email',
    'Date Submitted',
    'Technique',
    'Instrument',
    'Status',

In addition to that,  we will add 1 or 2 reports which will be having all the detailed information about the proposals. Hope my understanding is correct.

**Comment by Cat-Lucifer** [comment]
@deepaksftc Yes, this is perfect.  Thanks!
