### ISSUE TITLE
Lock down submit button to only user officers

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#1051]
Would should not allow the sec/chair to do the final meeting submit, that should be a user officer. 

This issue includes modifications to UOP to enable permissions (such as the final submission of FAP meeting results) to be configured in the frontend.

**Comment by joshhdawes** [comment]
@Cat-Lucifer I wanted to highlight this issue since I remember you mentioning that the current permissions for who can perform the final submission of a FAP meeting aren't really correct.

While the initial plan was to make permissions configurable, I think it would be a significant amount of work, and I'm not sure how much time we'd have for that (and when).

While we probably won't do anything at the moment, I just wanted to make you aware of this, especially if it's something that might need changing.
