### ISSUE TITLE
As a user officer, I want to upload a set of documents for each FAP

### ISSUE THREAD

**Issue by joshhdawes** [UserOfficeProject/user-office-project-issue-tracker#1123]
Currently, @Cat-Lucifer maintains a separate sharepoint site for FAP booklets. It would be better if FAP booklets could be uploaded into the proposal system, and be linked to their FAPs.

Additionally, for each continuation proposal, it would be useful for the previous experiment reports for those proposals to be uploaded to each relevant FAP.

Since there are also requirements for other documents, such as meeting guides, to be uploaded to the system, we need a generic document upload feature.

**Comment by joshhdawes** [comment]
@Cat-Lucifer we're currently having a chat with @georgeflecknell about this (it's come up in a meeting about XFAP), and he's mentioned that there can quite often be large numbers of experiment reports (up to 50) associated with FAPs, along with other documents (such as meeting guides and even site maps).

While we haven't discussed uploading things like meeting guides and site maps (so we're currently assuming we don't have to handle things like this), @TCMeldrum is wondering how we can deal with displaying (and enabling reviewers to browse) lists of up to 50 reports.

I know there are concerns about allowing reviewers to search such a list - would this be required? Or would it be acceptable to just show a really long list? Or could we even just upload a zip (would be surprised if this was okay, but thought I'd ask)?

**Comment by Cat-Lucifer** [comment]
@joshhdawes  If there are any other meetings about the XFAP site please can I be invited, since it is both George and I who are the main users of it.

I did mention meeting guides, etc. in our meeting, which is why I asked for a general file upload function per FAP, rather than specific listed items.  I have given you and @TCMeldrum access to the current XFAP site so you can have a nosy: https://stfc365.sharepoint.com/sites/FacilityAccessPanels-External

There are usually 30-40 continuation reports per round, but obviously this would mean fewer numbers per FAP.  So, not 50 docs per FAP.

Per FAP, there would be:
- 1 x FAP book
- Up to 10-ish continuation reports, which I could merge as one doc if needed

Common to all FAPs there would be:
- 6 x guide docs

Thinking about it, the common docs might be better placed in the Reviewer pages section, but I'm not sure how that would work.

**Comment by georgeflecknell** [comment]
@Cat-Lucifer 

Thanks for clarifying. For some reason I was counting continuations as PDFs and reports and suggested 50 as an absolute maximum. (booklet, guides, continuations). If a more realistic maximum is still ~10-15, would this be considered manageable without subfolders?
