### ISSUE TITLE
Remove unused test calls/templates on dev

### ISSUE THREAD

**Issue by ellen-wright** [UserOfficeProject/user-office-project-issue-tracker#1151]
### What is the problem and why is it a problem
We need to clear out the test calls and templates on dev. 
As well as agree on a way forward to avoid unused test calls/templates cluttering up dev. 

We should:
- Agree on a naming convention for test calls / templates 
- Maintain a  list of usable templates / calls 
- Delete unused test calls / templates 

This issue was raised by George in the teams channel.

**Comment by ACLay** [comment]
As mentioned in https://github.com/isisbusapps/local-db/issues/48, we may want to look at populating dev with a copy of prod. Don't know how appropriate an automated "clear out dev and populate from prod" might be, since we want to make sure we pull in recent config & questions, but also make sure we're not deleting test calls that anyone's using at the moment.

**Comment by simonfernandes** [comment]
Sprint planning notes:

We can clear out any calls and templates that expired before a certain date

**Comment by ellen-wright** [comment]
Un-needed calls and templates created before 2024 have been removed.

Email has been sent to developers to help keep dev clearer in the future.


> To avoid dev becoming cluttered in the future please can we ask that:
> 
> - If you create a test call, please make sure to give it a meaningful name. 
> - This will make identifying calls easier and avoid having lots called 'test'.
> - Once you are done with your test, please remove the call.
> - Once you have finished with a test template:
> - If it has no proposals attached, please delete the template. 
> - If it does have proposals the template can be archived.
