### ISSUE TITLE
Make publication title field longer

### ISSUE THREAD

**Issue by vyshnavi1605** [UserOfficeProject/user-office-project-issue-tracker#239]
Make the title field longer
![image](https://user-images.githubusercontent.com/72739242/137915446-ce42e956-dde0-4a29-b365-8a8f78436203.png)

**Comment by simonfernandes** [comment]
Publications are a type of generic/sub template (see [George's explanation](https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/633#issuecomment-1213048499) of how they work). 

I think this issue corresponds to the "generic template basis" that you have to provide. 

In this example, it asks the user for the publication title as the basis. The user is given a one-line input, but sometimes publication titles (or other bases) can be fairly long, so this isn't ideal because it will either hide part of it or limit it. We need to choose a different input suited to more text and ensure that the database column that this field corresponds to accepts enough characters.
