### ISSUE TITLE
LSF New Programme has no down stream processes in place

### ISSUE THREAD

**Issue by WhittyPM** [UserOfficeProject/user-office-project-issue-tracker#301]
Outcome from meeting with UO and LSF Sarah N - #297 

The system recognizes new programme proposals but everything down stream is not included. Current work round’s in place. Not high priority. It would be nice to have in the new proposal system.

 Emma G feels that an ideal way of approaching this when a new programme proposal is submitted they get LSF 4 digit number but if alongside that there could be a direct access number assigned to it. If it’s not successful then its fine, but if it is successful that direct access number can then follow downstream processes like the scheduler and FAP letters. #300

**Comment by ACLay** [comment]
Copying in outcomes from discussion on zoom and [teams](https://teams.microsoft.com/l/message/19:f0afa005ea5b474e83109a55c93c16f2@thread.skype/1653561378399?tenantId=3f66361c-a87e-4158-8f61-99e82db3cac8&groupId=403a668a-985f-445b-a4e3-b3a3070bb25b&parentMessageId=1653561378399&teamName=ISIS%20Computing%20Division%20Staff&channelName=Proposals%20and%20Outcomes&createdTime=1653561378399):

Reckon we've a plan of attack that we're gonna try and push through, given the short timescales (slightly adapted with some extra bits I've checked or thought of since):


	
- [ ] Say the UO have to stick with the LSF_prog 2022_2 convention that's in place from last time for calls that create new programmes
	
- [x] Patch allocations to ignore any incoming "proposals" that have prog in their call name - https://github.com/isisbusapps/proposal-allocations/pull/210
	
- [ ] The current "LSF Direct Access and Ongoing Programmes" template has a "Proposed route" question with options for "Direct Access" and "Programme Approved". We think this will need a followup dependancy question asking for the approved programme it's part of. Probably best to check with the UO. Look at this as a free text field, and have validation as a separate issue for later
	
- [ ] Find out from the UO how the last rounds new programmes were reviewed/approved. Figure out a long term solution later. Edward, when you did the manual sp upload was it just in the main proposals, do you remember doing anything for the programmes?
	
- [ ] We're not going to be manually creating access routes/calls and proposals for them for programmes and their proposals.
	
- [ ] Make sure the plan is communicated to the UO
	
- [ ] Find a better way to deal with programmes down the line that doesn't force programmes into a proposal shaped hole.

**Comment by ACLay** [comment]
We've met with Emma & Sarah from the user office to figure out the programmes process.

Historically:

- A proposal would be created in the programme call. Programmes request a number of weeks over 2-5 years and have a 6 page science case rather than 2, and an experiment number in the format "LSF 1234"
- Once approved at FAP, direct was reopened and successful programme proposers were asked to create a "direct approved programme" proposal.
  - To avoid users having to do a duplicate proposal, the User Office took over this step
- The proposal would then go through to the scheduler.
- In future rounds a proposer would create a new "direct programme approved" proposal saying what they want to do this time and how it's been going

Requirements for now:

- As before, we don't want the programme proposal to be put in the Proposal_List_LSF on sharepoint
- We still want a normal direct experiment reference number to be generated for a programme's first part
- This should get through to the scheduler
- We'd like to avoid having a user recieve new submission emails for the first programme part.
  - They should be told "this is the experiment number for your programme's first part"
- The current round needs to be sorted by 4th July, but preferably ASAP.
- Look for automated solution, but use a manual process for this round if needed

**Comment by ACLay** [comment]
Design review:
- Process seems okay.
- Manual process for the initial four. Talk to george if we're missing any data to submit them in allocations.
- First iteration on automated system as a Jenkins CLI thing. Adding a UI for this and a couple other similar style tools should be addressed separately.
- Forward the initial RB's to S&O to make sure everything went through properly.

**Comment by ACLay** [comment]
Thoughts on the app for this:

- This tool should go in a new isisbusapps repo. Maybe "approved-experiments"
- Do it as a node/typescript app.
  - Keeps it in the same languages that many of our other apps
  - Should be easy to add packages and node commands for a web interface later
- Eventual web interface on `<dev>office.facilities.rl.ac.uk/approvedexperiments`
  - Restrict it to the User office and developers AD groups.

**Comment by TickleThePanda** [comment]
> This tool should go in a new isisbusapps repo. Maybe "approved-experiments"

Would putting it into `proposal-allocations` be reasonable here? It feels to me that the focus is allocating on pre-approved proposals. Depending on the outcome of this, it could be part of a future `office.../allocations` interface.

> Will need to take arguments for...

Could this be done from a CSV (or something) from the start in the CLI? Bringing that down to the single case is easier than creating two interfaces, I think.

**Comment by ACLay** [comment]
@TickleThePanda Could you create a repo for this?

**Comment by TickleThePanda** [comment]
Can do!

> we no longer have repo count limits

Just to be very clear, I didn't suggest the same repo because I want to limit the number of repos. I think it's likely that this frontend would be coupled with allocations (and so would be released at the same time) and for the potential that this functionality will be combined with the rest of the frontend of allocations in the future. If we do end up doing either of these things, I think we should combine the repos.

**Comment by TickleThePanda** [comment]
https://github.com/isisbusapps/approved-experiments/

I've created the repo. Let me know when you've pushed some code and then I can add branch protection.

**Comment by ACLay** [comment]
> I've created the repo. Let me know when you've pushed some code and then I can add branch protection.

I've pushed the initial commit to `master` and `develop`

**Comment by TickleThePanda** [comment]
Added branch protection and codeowners.

**Comment by ACLay** [comment]
We're expecting the next LSF FAP meeting mid september. Will need the initial tool in place around then.

**Comment by TickleThePanda** [comment]
We were unsure how to run this (if it can be ran now) so some documentation would be handy!

**Comment by ACLay** [comment]
The plan is to allow these to be created via the new approved experiments webapp, due to release in the next sprint https://github.com/isisbusapps/approved-experiments/issues/35
