### ISSUE TITLE
Make labelling more friendly 

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#633]
Labelling could be more friendly. For instance, when entering Sample information we get a box headed ‘Generic Template Information’ and ‘New Sub Topic’.

**Comment by georgeflecknell** [comment]
Can't find a problem in either questionnaire edit or questionnaire fill with these headings ‘Generic Template Information’  ‘New Sub Topic’.

![image](https://user-images.githubusercontent.com/75302934/184343100-c071ae86-2dae-4e47-91c0-1bbbbff01fcc.png)

It's possible that the labelling has already been improved in the questionnaire.

**Comment by georgeflecknell** [comment]
**PLEASE NOTE: sub-template is the same thing as generic-template**

This issue refers to the way sub-templates are displayed in a questionnaire. If a sub-template is created and added to a proposal but without first amending the topic names in that sub-template.

The following screenshot shows the proposal submission form where that proposal contains a sub-template as a topic

![image](https://user-images.githubusercontent.com/75302934/184350887-bc1a3c8c-d051-4954-85ac-a0eec6a405ca.png)

After clicking Add we get a modal in which there are two topics named (New Sub Topic and New Topic). This occurs because those topics haven't been renamed during creation of the sub-template.

The problem with the box header "Generic Template Information" has been resolved and now the question title of the sub-template in the overall proposal template appears as the modal heading.

![image](https://user-images.githubusercontent.com/75302934/184351674-a83842bd-6f02-4fea-9a14-9e5859965825.png)

**Comment by georgeflecknell** [comment]
No actual problem found. Labelling is only unfriendly when a sub-template is incorrectly created and pulls through generically named headings as a result.
