### ISSUE TITLE
Lots of unhandled NODE exceptions in STFC logs

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#707]
There are dozens of `ERROR - Unhandled NODE exception` exceptions that sometimes show up in STFC backend logs. The vast majority of these is caused by failing to log out a user, and they are accompanied by warn level logs: `WARN - Failed to log out user`. This makes sense since we log the warning and then throw the error in this event.

**Comment by simonfernandes** [comment]
A stab in the dark is that we aren't awaiting the call to the async logout function in some places. For example, [in the backend](https://github.com/UserOfficeProject/user-office-backend/blob/b561245e4a8f814b05331f19199831941092df7b/src/mutations/UserMutations.ts#L514), and in various places [in the frontend](https://github.com/UserOfficeProject/user-office-frontend/blob/develop/src/components/user/SharedAuth.tsx#L60).

**Comment by ACLay** [comment]
For the log out failures my **suspicion** is that when a token is expired each failed web request results in a call to the logout mutation, and since logout doesn't have the same promise cacheing used for some other methods, each of our backends logout calls tries (and fails) to call the UOWS logout.

It's not at the same quantity, but by calling the logout UOWS method directly with my sessionID, and refreshing the proposals front page I am able to force a couple of Unhandled NODE exception's into the logs: 
![image](https://user-images.githubusercontent.com/2938284/189324362-1dfbafa1-96f2-4afd-bd0b-16bcbcce730f.png)

**Comment by TCMeldrum** [comment]
Had a look this morning and there have been very few of these errors since the October release I am guessing something in that release fix this:
![image](https://user-images.githubusercontent.com/81559866/215472274-8ddb7f61-96cc-47aa-b454-5d80e048f0b1.png)
I would be happy to close this issue if others agree

**Comment by mutambaraf** [comment]
Have not seen those either. I am also fine with this being closed.

**Comment by ACLay** [comment]
Have we had any large proposal deadlines since then? This was something that I recall ramped up in the runup to previous ISIS deadlines, and we might just not have had the traffic to trigger the errors in any significant quantity since then

**Comment by TCMeldrum** [comment]
There have been 10 of those errors since the release and all in one day. On dev as well there have been 1 since October last year when they were pretty common before then

**Comment by TCMeldrum** [comment]
Looking at the logs around the 10 instances there seem to have other problems like not connecting to the DB and failing to setup rabbitmq.

**Comment by TCMeldrum** [comment]
Pretty sure this was fixed by the October release
