### ISSUE TITLE
Instances of "No response received from server" in STFC backend logs

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#712]
We noticed at stand up that from Sep 22, 2022 @ 10:42:02.545 to Sep 22, 2022 @ 10:50:39.733 there was a large spike of errors originating from the proposal backend:

`[2022-09-22T09:42:07.059Z] ERROR - Error received from client {"error":"{\"userMessage\":\"No response received from server\",\"error\":{}}"}`

**Comment by simonfernandes** [comment]
- The backend ping job passed during this time period.

- The log before the first error was:
`Sep 22, 2022 @ 10:41:53.273
[2022-09-22T09:41:53.273Z] INFO - Creating dummy users {"usersIds":[1121597]}`

- The first log after the error spike was (note the large number of cache hits):
`Sep 22, 2022 @ 10:54:46.483
[2022-09-22T09:54:46.483Z] INFO - Cache statistics for the last 300 seconds   {"cache":"uowsBasicUserDetailsCache","stats":{"hits":736,"misses":0,"additions":0,"updates":0,"removals":0,"entries":200,"maxEntries":200},"loggingFrequencySeconds":300}`

**Comment by TCMeldrum** [comment]
Bit stumped on where to start on this one, not really sure where to start or what could have caused it. The user `1121597` was a new account that day so that may have had something to do it? Other than that I found more logs with high cache hits from around that time: `{"cache":"uowsRolesCache","stats":{"hits":45978,"misses":1,"additions":1,"updates":0,"removals":0,"entries":93,"maxEntries":200},"loggingFrequencySeconds":300}`  and `{"cache":"uowsRolesCache","stats":{"hits":58415,"misses":93,"additions":1,"updates":92,"removals":1,"entries":93,"maxEntries":200},"loggingFrequencySeconds":300}` and a few more. Any ideas?

**Comment by mutambaraf** [comment]
Might look at this separately the frontend and backend .See which logs come first .But unless there is some way requests a held up and then sent at once have no idea.

**Comment by TCMeldrum** [comment]
Can't replicate the issue, and the logs are ultimately unhelpful. We haven't seen anything like it since so hoping it is a one-off.
