### ISSUE TITLE
Proposal templates appearing as blank

### ISSUE THREAD

**Issue by voduguwa** [UserOfficeProject/user-office-project-issue-tracker#746]
When you go to edit a proposal template, it appears to be blank - this is an issue for all proposal templates. New templates and cloned templates also appear blank. Proposals can be submitted to calls just fine but proposals templates cannot be made or edited.

## Why it needs to change.
It affect everyone's ability to create new proposal templates

## Other helpful details like screenshots or email content from.
The proposal template is blank and an error message appears:
![image](https://user-images.githubusercontent.com/108725376/199519258-7c618368-67c3-40e6-ba12-48a222e162bc.png)

logging error: 
![image](https://user-images.githubusercontent.com/108725376/199519661-7ac2e009-8709-4e0f-bb74-1cbb117c1d4a.png)

**Comment by simonfernandes** [comment]
Fixed this manually for now but it needs further investigation.

All of the templates seemed to be failing due to one particular question (id: `text_input_1637065575908`). This text_input question config should have a min and max that is integer | null, but somehow the max had a value of "". Changing this to null in the database seems to have fixed all of the templates.

I have no idea how it changed, but it apparently was last updated a couple of days ago at 4pm (see screenshot). When the dev logs are back up we should try to figure out how this changed.

![image](https://user-images.githubusercontent.com/14293717/199526861-43a12156-6880-4531-a1f5-383e5a00af25.png)

**Comment by TickleThePanda** [comment]
We should check if any min/max fields have `""` instead of `null` in prod.

**Comment by simonfernandes** [comment]
> We should check if any min/max fields have `""` instead of `null` in prod.

There are no more instances of this on dev or prod so I'll close this for now.

```sql
SELECT *  FROM questions WHERE default_config::json->>'max' = '' OR default_config::json->>'min' = ''
```

**Comment by mutambaraf** [comment]
I am on the view this issue might need to me reopened @simonfernandes given the recent reoccurrence by @Scott-James-Hurley .Details `For context some changes to some of ISIS proposal questions in the Rapid and Dutch Access routes this morning. This may or may not have some bearing on the issue.`

**Comment by simonfernandes** [comment]
Do you mind opening a new issue @mutambaraf ?

Sounds like there is something in the questionnaire setup that incorrectly gives an empty string to min/max values, and then this affects both viewing the template as a user officer (this issue) and accessing the call as a user (Scott's issue). 

Is this your understanding too?

**Comment by mutambaraf** [comment]
Okay will open a new issue. Thanks
