### ISSUE TITLE
Investigate Presto DB or data warehousing solutions for cross database queries

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#755]
Having some form of self-serve solution would be useful.

 - Data warehousing https://prestodb.io/ + existing reporting tool/new reporting tool
 - Pre-build reporting solution

**Comment by simonfernandes** [comment]
# What is Trino
Trino is a "SQL query engine" that allows you to query large amounts of data from multiple sources, including relational databases like Postgres and Oracle. It essentially acts as an interface for these data sources. Trino queries are written in ANSI SQL specification and allows querying multiple data sources in the same query ("query federation").

# Trino vs Presto
Trino and Presto are extremely similar. They seem to have the same functinoality and architecture. Presto was developed by Facebook and in 2019 development of it forked, creating Trino. I am suggesting Trino instead of Presto for a few reasons:

- Presto is "built to make queries more efficient for hyper-scale internet companies" and Trino is "built for a much broader variety of customers and use cases".
- [Trino](https://github.com/trinodb/trino) seems to have more developer involvement and interaction than [Presto](https://github.com/prestodb/presto).
- The Trino documentation is clearly based on Presto's (they share many of the same sections and wording), but I've seen examples where Trino's is more detailed.
- Client library support is similar. Some of the Trino libraries are the same as the ones used for Presto, and vice versa.

# Trino concepts
## Workflow
1. A **client** executes a query. Clients include the built in CLI, tools like Metabase, software with client libraries, or anything capable of sending API calls like Postman. The client sends the query to the coordinator.
2. The **coordinator** receives the query. It acts as the brain of Trino and is responsible for parsing the statement, planning queries and managing workers via an internal REST API.
3. The **workers** receive instructions from the coordinator. They fetch and process data and communicate with other workers via REST.

## Connecting to data sources
- A **connector** adapts Trino to a data source, and is like a database driver. Trino has several built-in connectors, including ones for Postgres and Oracle.
- **Catalogs** reference a connector and a data source in a configuration file. Trino SQL statements executed on a client can run against multiple catalogs for federated querying. An example catalog might be a four line text file specifying the Oracle connector, the ISISUSERDB connection string, and the credentials.

# Deployment
Trino can run in a Docker container locally and can be deployed to Kubernetes with an optional Helm chart.

# Security
- It's strongly recommended to use a [load balancer or proxy server](https://trino.io/docs/current/security/tls.html#use-a-load-balancer-to-terminate-tls-https) and keep the TLS configuration there, instead of securing Trino directly. There's a tiny bit of additional configuration for when Trino receives a request via HTTP to tell it that TLS has already been negotiated via proxy.
- There are multiple ways of authorisation, but for REST requests, username and password auth must be used. This involves adding users and passwords in files within Trino, and the request must then include an authorisation header with the Base 64 encoded user and password. 

# Querying
Trino uses ANSI SQL and there is documentation on the site for this. When querying multiple data sources in the same query, you must reference the catalog and schema in `catalog.schema.table.column` format, but you can use aliases.

Using Postgres as the origin database (i.e. joining Oracle tables) I have successfully tried:
- Queries that include Postgres JSON.
- A large query to join reporting person names to all PIs in the database (14k+ rows)
- A Direct 23/1 query to show various user information for all PIs and Co-Is.
- A simple join to a view that isn't reporting_person.

There are more queries that I had for Direct 23/1 that I would like to have tried, but adapting Postgres queries to ANSI SQL is a bit fiddly. The JSON functions are the most frustrating part.

# Choosing a client
## Reporting Tool
Trino doesn't have a free, open-source ODBC driver unfortunately (Windows .NET interface to interact with Trino). It would require [purchasing a licence](https://www.magnitude.com/drivers/trino-odbc-jdbc). 

We would need to implement a REST client to interact with the [Trino REST API](https://trino.io/docs/current/develop/client-protocol.html) to make query requests, where results are returned in JSON. Each reponse will contain a limited amount of data, so for a large results set, the response will include a link to the next request needed.

## Metabase (or similar)
Metabase is a BI tool that allows you to "explore your data in a user-friendly interface", and is what the ESS are using for their reporting needs. When I tried out Metabase, it was quick and easy to get up and running with Trino. Starburst (a paid, enterprise version of Trino) has a free driver to connect Metabase and Trino.

Although a lot of Metabase is very easy to interact with and it has many automatic examples, it would require some thought on how we should best organise availability of data. You can have saved queries/reports, but not user inputted parameters. Instead I think you would use views of data and utilise filtering.

The open-source version doesn't include audit logs, and it doesn't include a feature to hide rows/columns of data, which might have been useful for hiding account emails and facility-specific data.

**Comment by simonfernandes** [comment]
Outcome from design review:

- Proceed to deploy Trino
- Once deployed, change the Reporting Tool to make REST requests for relevant proposal queries
