### ISSUE TITLE
How do we interact with SharePoint online?

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#808]
Refs UserOfficeProject/user-office-project-issue-tracker#802

What metadata do we need in SharePoint as a minimum?

Do we need to have a programmatic integration for this round?

If we need one, how do we do that?

**Comment by voduguwa** [comment]
After a discussion with George and Dylan, it has been concluded that: 

The minimum metadata needed will just be the RB number as the name of the proposal PDF. Also, proposals can be downloaded into a single folder, rather than being sorted into separate FAP folders. 

Programmatic integration will not be necessary as long as we have a solution that consistently creates a network folder with appropriately named files. To get these files into SharePoint, Dylan is fine to run regex then attach them to proposal items (deleting the original file after). As for viewing permissions, owners will be able to view during staging and after uploading, people on corresponding panels will be able to view them - as expected.

**Comment by ACLay** [comment]
So is the plan just to send Dylan a bunch of PDFs (or a link to a folder with them) and RB numbers for them, and then he'll handle it all from there?

**Comment by voduguwa** [comment]
> So is the plan just to send Dylan a bunch of PDFs (or a link to a folder with them) and RB numbers for them, and then he'll handle it all from there?

Yes

**Comment by ACLay** [comment]
👍 Seems fine to me.

**Comment by voduguwa** [comment]
> 👍 Seems fine to me.

Okay, thanks for the feedback :)
