### ISSUE TITLE
Find out how HPL FAP booklets are generated

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#840]
We need to find out how the FAP booklets work from the User Office. We may then need to look at their software in more detail so that we can ensure that we'll have everything set up correctly.

One particular area highlighted is, if they use the MS Access tool, it may require PDFs to be in a certain place, which they might not be when using the new software.

**Comment by EdwardHaynes** [comment]
I've spent some time looking into this one and it's really unclear to me how this tool ever generated the booklets, although it is a bit of a maze so I might be missing something. I don't think it's a massive issue because the book itself isn't very complicated and should be easy to reverse-engineer.
