### ISSUE TITLE
Investigate how to give FAP panel members the correct SEP reviewer and SEP secretary roles 

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#869]
Currently, STFC sets all user roles in the `STFCUserDataSource.ts` we need to investigate and implement a way of either pulling through the FAP Panel member role or if we should adopt the current User management feature to give people the associated roles. There is an active directory group for FAP members we could use, `ISIS_FAP` but there might be other groups we need to look at. If membership is managed through active directory groups we need to know how they are kept up to date.

**Comment by simonfernandes** [comment]
In the existing Access tool there's a way to check that everyone's Fed ID for an upcoming panel is active (and reinstate if necessary), and automatically add them all to the `ISIS_FAP` AD group. That is (or was) needed so that they have permissions to view an old SharePoint FAP site (XFAP) with all of the proposal PDFs.

**Comment by Scott-James-Hurley** [comment]
This issue seems closely linked to #868. Might be an idea if @EdwardHaynes and I have a chat at some point to decide if we're going to use new proposal's SEP member management and if we're going to use active directory or import all it's historical data to the postres db.
