### ISSUE TITLE
The questionnaire names a 3 page file limit for science case in HPL, it is possible to upload 4 pages

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#957]
Minor issue:
The questionnaire names a 3 page file limit for science case in HPL, it is possible to upload 4 pages

Raised by David Carroll.

Not a pressing issue but if possible please resolve before round start.

**Comment by simonfernandes** [comment]
Sprint planning notes 15/11/23:

- Are certain PDFs made with certain software causing issues?
- Relying on submitters to keep within limits

**Comment by simonfernandes** [comment]
@georgeflecknell and @Cat-Lucifer Was this for the HPL Vulcan shutdown call? Because it looks like both of those questions in that template (science case and tech spec) are set to unlimited pages.

**Comment by Cat-Lucifer** [comment]
@simonfernandes No, this was for the HPL template, where the science case upload is set to 3 pages:

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108054517/2592112a-88c2-45d5-857e-3513d4d0f7eb)

**Comment by simonfernandes** [comment]
@Cat-Lucifer Ah thanks Emma. I was having a look at our logs (screenshot below) as it shows the outcome of the PDF page count check at the time of upload. Frustratingly it's quite longwinded to distinguish which proposal and call each entry belong to! (Since we re-use the same question for all templates but have different configurations for it). The two ticked seem to be related to your test proposal Emma and they mention the 1 page test PDF currently in place. The ones before that in the timeline are skipped due to unlimited page count seem to be from VulcanSD. And you can also see some after that have not passed the check. No sign of the 5 page PDF you previously mentioned.

If you want to have another fiddle and give me the rough time window you do it in then I'm happy to have another check. I didn't like to change anything myself.

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/14293717/3605a3fc-e8f0-4370-b3de-a9ffe93c384d)

**Comment by Cat-Lucifer** [comment]
@simonfernandes Yeah, that's annoying to trawl though.  I'll do another test call submission next week and let you know the time and date of the submissions - I'll try a compliant and a non-compliant submission.

**Comment by Cat-Lucifer** [comment]
@simonfernandes This is not an issue anymore.  Page constraints work fine.

![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108054517/2d0e0aad-c9d3-4517-82c0-60f8ddf57dd1)
