### ISSUE TITLE
Increase in proposal pdf download failures

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#985]
We have see an increase in proposal download errors. With some investigation looks like the connection between the proposal backend and factory breaks while a proposal is being generated.

### What is the problem and why is it a problem
All roles and integrated applications  will sometimes fail to download a given proposal.

### Steps to reproduce (if it's a bug).

`Failed to generate the requested file(s) 
 {"err":{"error":"AbortError: The operation was aborted","message":"Could not download generated pdf/proposal"},"originalUrl":"/download/pdf/proposal/17176"}}}`

**Comment by mutambaraf** [comment]
Was able to reproduce the error with proposal primary key `16264`.This is a short list of proposals primary keys that logged some errors  `17313,17308,17316 and 16264`

**Comment by simonfernandes** [comment]
Sprint notes: 

Investigate whether this is related to the proxy timeout issue found in the results letters by R&A (https://github.com/isisbusapps/fba-reverse-proxy/issues/289)

**Comment by simonfernandes** [comment]
It seems to be because the factory times out while executing a select query to the database. The backend will log "Could not download generated pdf/proposal" and then 15 minutes later we get a timeout log in the factory:

```json
{"error":{"errno":-110,"code":"ETIMEDOUT","syscall":"read"},"obj":{"__knexUid":"__knexUid47","__knexTxId":"__knexUid47","method":"select","options":{},"timeout":false,"cancelOnTimeout":false,"bindings":["bc518e4b-88cb-4441-ad34-b05ed13b69ca"],"__knexQueryUid":"LQkti7R7b-H4wXZmA5yGC","sql":"select \"file_id\", \"oid\", \"file_name\", \"mime_type\", \"size_in_bytes\", \"created_at\" from \"files\" where \"file_id\" in ($1) and mime_type ~* '(application\\/pdf\|^image\\/.*)' order by \"file_id\" asc"}}
```

These timeout errors have been happening for at least the past 6 months (beginning of August) with a peak of about 28 times a day in October around when ISIS Direct closed.

We have seen a large increase in these "Could not download generated pdf/proposal" errors since 10th January, but that is when we released a new version of the backend that contained some [changes to the logging](https://github.com/UserOfficeProject/user-office-core/pull/444).

So I think that actually, although it looks like there has been an increase, this has been an ongoing problem for a while and hasn't gotten any worse. From a user perspective it is the issue where the PDF download seems to hang (https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/718) that we have been aware of for over a year now.

**Comment by simonfernandes** [comment]
I made a change to the [connection pool recommended minimum](https://github.com/UserOfficeProject/user-office-core/pull/521) which was released to production on 28th February. Logs show we haven't had a single `etimedout` error from the factory since this date:

![image](https://github.com/UserOfficeProject/issue-tracker/assets/14293717/d14618ef-ac4b-4ed0-bc3d-bac257bdc380)
